services:
  # The Inference Engine
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-server
    ports:
      - "8081:8080"
    volumes:
      - ./models:/models
    #command: "-m /models/HY-MT1.5-1.8B-Q8_0.gguf --host 0.0.0.0 --port 8080 -c 4096 -ngl 99"
    command: "--models-dir /models --host 0.0.0.0 --port 8080 -c 4096 -ngl 99"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # The Frontend
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - 'OPENAI_API_BASE_URL=http://llama-server:8080/v1'
      - 'OPENAI_API_KEY=not-needed'
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - llama-server

volumes:
  open-webui: